prevent infinite loops
flowerpowerdao/power-equalizer pull request #105
Opened 2023-06-19 06:22 UTC by ZenVoich

2023-06-23 13:27 UTC, ZenVoich commented on src/Disburser/lib.mo
>                switch (res) {
remove switch and add `i` to memo

2023-06-23 13:35 UTC, letmejustputthishere requested changes

2023-06-23 13:35 UTC, letmejustputthishere commented on src/Disburser/lib.mo
> +                case (#Err(#InsufficientFunds(_))) {
remove switch

2023-06-23 13:35 UTC, letmejustputthishere commented on src/Disburser/lib.mo
add "nonce" to memo. value between 0-100

2023-06-23 13:35 UTC, letmejustputthishere commented on src/Marketplace/lib.mo
> +        };
can be removed

2023-07-07 14:12 UTC, letmejustputthishere approved these changes

2023-07-07 14:12 UTC, merged