Remove bulk sale
flowerpowerdao/power-equalizer pull request #112
Opened 2023-07-03 10:15 UTC by ZenVoich

fixes #98

2023-07-07 13:58 UTC, ZenVoich commented
remove `amount` from `reserve`

2023-07-07 14:04 UTC, letmejustputthishere requested changes

2023-07-07 14:04 UTC, letmejustputthishere commented on src/Sale/types.mo
> +    bulkPricing : [(Nat64, Nat64)]; // always [(1, <price>)]
remove bulkPricing entirely

2023-07-07 14:04 UTC, letmejustputthishere commented on src/main.mo
> +  public func reserve(amount : Nat64, quantityNOTUSED : Nat64, address : SaleTypes.AccountIdentifier, _subaccountNOTUSED : SaleTypes.SubAccount) : async Result.Result<(SaleTypes.AccountIdentifier, Na
remove unused arguments as we control the sale frontend

2023-07-07 14:04 UTC, letmejustputthishere commented on src/main.mo
> +  public func reserve(amount : Nat64, quantityNOTUSED : Nat64, address : SaleTypes.AccountIdentifier, _subaccountNOTUSED : SaleTypes.SubAccount) : async Result.Result<(SaleTypes.AccountIdentifier, Na
also gret rid of amount

2023-07-28 13:34 UTC, letmejustputthishere approved these changes

2023-07-28 13:41 UTC, merged